Mighty-Morphin-Coders/grace-shopper

- .gitignore
- package-lock.json
- package.json
- server/db/db.js
- server/db/index.js
- server/db/models/User.js
- setup basic db connection (db.js)
- setup init connection to be used in server.js (index.js)
- setup User table (models/User.js)
> Model setup

- .gitignore
- package-lock.json
- package.json
- server/db/db.js
- server/db/index.js
- server/db/models/User.js
puts curly braces and commas back where they needed to be in the package.json and the package-lock.json
> Package lock

- package-lock.json
- package.json
- public/index.html
- server/db/index.js
- server/index.js
- set up basic server
- connected server to db
- setup basic api route for index.html file
- installed express, nodemon dependencies
> setup: built basic server, connected to db

- package-lock.json
- server/index.js
-updated port to have process.env.port to precede 9000
> update: updated port

- package-lock.json
- server/db/models/User.js
- server/index.js
made a minor change to the User Model field. I added the isEmail: true, validation and changed the defaultemail to defaultemail@gmail.com, nothing major!
> added email validation in User Model

- server/db/index.js
- server/db/models/Product.js
- server/db/models/User.js
Hey guys I just added the product model!
> finished product model

- package-lock.json
- server/db/index.js
- server/db/models/Order.js
Sets up order model and association between order and product models as well as a through table
> model-order

- server/db/index.js
- server/db/models/Order.js
- server/db/models/Order_Product.js
- server/db/models/Payment_Method.js
creates the payment_method model, updates the order_product model to include quantity of each item, updates order table
> feature/update: updates order, order_product models and creates payment_method model

- server/db/index.js
- server/db/models/Category.js
- server/db/models/Order.js
- server/db/models/Product.js
- server/db/models/Review.js
Finished models and relationships!
> update:finished models and relationships

- server/api/routes/orderRoute.js
- server/api/routes/productRoute.js
- server/api/routes/userRoute.js
- server/index.js
created routes for:
- users, 
- products,
- orders.
> update: created basic routes

- server/api/routes/productRoute.js
- server/api/routes/reviewRoute.js
added a reviews mount to product
> updated productRoute

- server/api/routes/orderRoute.js
- server/api/routes/productRoute.js
- server/api/routes/reviewRoute.js
- server/api/routes/userRoute.js
- server/db/index.js
- server/db/models/Review.js
- server/db/seed.js
- server/index.js
- added basic users
- added post and put routes
- created basic seed file
> update: seeded users, added post and put routes

- .travis.yml
- server/db/index.js
- server/db/seed.js
- test/spec.js
Testing to see if travis is working with product test.
> testing travis

- .travis.yml
- server/db/index.js
- server/db/seed.js
- test/spec.js
- test/testDb.js
yo dawg, travis gave me a hard time but i gave him all the smoke. see if he still got something to say.
> fixed travis spec files

- server/db/models/Order.js
- server/db/seed.js
added in seed data for the following models:
- reviews,
- orders,
- order_products
also sanitized some of product data
> update: added order, order_products, review seed data

- server/db/models/User.js
Added a unique constraint for the user's email
> feature: added unique constraint to the model-user

- server/api/routes/orderRoute.js
- server/db/index.js
- server/db/models/Order.js
- server/db/seed.js
- updated relationship between order and product to be belongsToMany both ways
- added class method to return all products associated to an order
> update: updated Order class method

- client/store/actionCreators/categoryActionCreator.js
- client/store/actionCreators/orderActionCreators.js
- client/store/actionCreators/productActionCreators.js
- client/store/actionCreators/reviewActionCreators.js
- client/store/actionCreators/userActionCreators.js
- client/store/actions/index.js
- client/store/reducers/index.js
- client/store/reducers/productReducer.js
- client/store/store.js
- server/api/routes/orderRoute.js
- server/db/models/Order.js
- server/db/seed.js
- built folder structure for store in client
- created action
- created action creators
- created reducers
> update: started building store

- package-lock.json
- package.json
- test/app.js
- test/spec.js
- test/testDb.js
Hey guys, I added 5 more test specs to the database. Hopefully Travis doesn't have an issue with it. Please review it when you get a chance.
> update: added more test specs for routing purposes

- test/spec.js
Had a type in one of the describes that I fixed.
> minor update: test specs cleanup

- client/store/reducers/index.js
- client/store/reducers/reviewReducer.js
Exported reviewReducer and brings it up into the rootReducer
> feature: exported reviewReducer and brings it up into the rootReducer

- server/api/routes/userRoute.js
> quick save

- client/store/actionCreators/reviewActionCreators.js
- client/store/thunks/orderThunk.js
- client/store/thunks/reviewThunk.js
- completed review thunks
- almost completed order thunks
> update: almost completed thunks

- server/api/routes/categoryRoute.js
- server/db/index.js
- server/db/models/Category_Product.js
- server/db/seed.js
- server/index.js
adds Category_Product model/through table and its instances, and creates routes to CRUD categories
> Categories

- client/store/actionCreators/categoryActionCreator.js
- client/store/actions/index.js
- client/store/reducers/categoryReducer.js
- client/store/thunks/categoryThunk.js
> update: added category thunk and created single category actions and reducer

- client/components/App.js
- client/components/NAVBAR/Login.js
- client/components/NAVBAR/Navbar.js
- client/components/USERS/AllUsers.js
- added additional logic for NavBar
- issue with re-rendering navbar login (we're close though)
> update: updated navbar login

- client/components/App.js
- client/components/NAVBAR/Navbar.js
- client/components/USERS/AllUsers.js
- client/components/USERS/EditUser.js
- client/components/USERS/SingleUser.js
- client/store/reducers/userReducer.js
- client/store/thunks/userThunk.js
Users, Single Users, edit users functionality
> User tests branch

- client/components/CATEGORIES/AllCategories.js
- client/components/CATEGORIES/CreateCategory.js
- client/components/CATEGORIES/EditCategory.js
- client/components/CATEGORIES/SingleCategory.js
- client/components/USERS/AllUsers.js
- client/components/USERS/EditUser.js
- client/components/USERS/SingleUser.js
- client/store/thunks/categoryThunk.js
- server/api/routes/categoryRoute.js
- server/api/routes/userRoute.js
> update: added middleware for routing and fixed categories on change

- client/components/App.js
- client/components/CART/Cart.js
- client/components/ORDERS/AllOrders.js
- client/components/PRODUCTS/AllProducts.js
- client/store/thunks/orderThunk.js
- client/store/thunks/userThunk.js
- server/api/routes/orderRoute.js
- server/api/routes/userRoute.js
- full backend to frontend functionality for creating a cart when there isn't a cart
- added api middleware to authenticate users trying to access api routes
> update: Cart frontend

- client/components/CART/Cart.js
- client/components/PRODUCTS/AllProducts.js
- client/components/PRODUCTS/SingleProduct.js
- client/store/thunks/orderThunk.js
- server/api/routes/orderRoute.js
- server/api/routes/userRoute.js
- completed add cart functionality from all products and single product page
- started delete functionality from cart view
> update: Continued cart3

- client/components/App.js
- client/components/PRODUCTS/CreateProduct.js
- client/components/PRODUCTS/EditProduct.js
- client/store/thunks/productThunk.js
- server/api/routes/productRoute.js
- server/api/routes/userRoute.js
admin can add and edit products
> feature: Add edit product

- client/store/thunks/userThunk.js
- server/api/routes/userRoute.js
> updated delete route for admin to delete a user as well as user destroy thunk with token added to it

- client/components/CART/Cart.js
- client/components/NAVBAR/Login.js
- client/store/thunks/userThunk.js
- package-lock.json
- public/index.html
- server/api/routes/authRoute.js
- server/api/routes/userRoute.js
- server/db/db.js
- server/db/models/User.js
- server/index.js
Added github oAuth, still need to fix some navbar issues and need to possibly update user model fields for last name.
> O auth and settings

- server/db/models/User.js
- server/index.js
> updated user model for signing up with user for oauth purposes

- client/components/USERS/EditUser.js
- client/components/USERS/SingleUser.js
- client/store/thunks/userThunk.js
- server/api/routes/userRoute.js
> update: Continued cart

- client/components/App.js
- client/components/CATEGORIES/AllCategories.js
- client/components/NAVBAR/Login.js
- client/components/NAVBAR/Navbar.js
- client/components/NAVBAR/Settings.js
- client/components/ORDERS/AllOrders.js
- client/components/PRODUCTS/AllProducts.js
- client/components/PRODUCTS/EditProduct.js
- client/components/PRODUCTS/SingleProduct.js
- client/components/USERS/AllUsers.js
- client/components/USERS/SingleUser.js
- client/store/thunks/orderThunk.js
- public/style.css
- server/api/routes/authRoute.js
- server/api/routes/userRoute.js
- server/db/models/User.js
-guests can now browse the site and add to cart
- conditional on a hard refresh
> update: connected guest functionality

- client/components/CART/Checkout.js
- package.json
- server/api/routes/orderRoute.js
stripe fully functional including alert
> feature: user can pay with stripe and gets a notification

- client/components/CART/Cart.js
- client/components/NAVBAR/Login.js
- client/store/actionCreators/orderActionCreators.js
- client/store/actions/index.js
- client/store/reducers/orderReducer.js
- client/store/thunks/orderThunk.js
- package-lock.json
- public/style.css
- server/api/routes/orderRoute.js
- server/index.js
- almost done cart functionality (have to add increment functionality from cart)
- fixed guest functionality
> update: continuedCart6

- client/components/NAVBAR/SearchBar.js
- client/components/PRODUCTS/AllProducts.js
- client/store/actionCreators/productActionCreators.js
- client/store/actions/index.js
- client/store/reducers/productReducer.js
- client/store/thunks/productThunk.js
- package-lock.json
- server/api/routes/orderRoute.js
- server/api/routes/productRoute.js
- server/index.js
some search bar updates made. will add routing functionality tmmr.
> Search bar updates

- client/store/reducers/productReducer.js
Less strict with searching for products now. Please look over and make sure everything is okay.
> changed substr in productReducer for filter to includes instead

- client/components/CART/Cart.js
- client/components/CATEGORIES/AllCategories.js
- client/components/CATEGORIES/SingleCategory.js
- client/components/NAVBAR/Login.js
- client/components/NAVBAR/Navbar.js
- client/components/PRODUCTS/AllProducts.js
- client/components/PRODUCTS/SingleProduct.js
- client/components/REVIEWS/CreateReview.js
- client/components/REVIEWS/ProductReviews.js
- package-lock.json
- public/style.css
- built basic css structure
- added motion elements where necessary
- added emoji renders
> update: built basic css structure

- client/components/PRODUCTS/SingleProduct.js
- client/components/REVIEWS/ProductReviews.js
- package-lock.json
- server/db/seed.js
> changed seed file and capital letters

- client/components/App.js
- client/components/CART/Cart.js
- client/components/CART/Checkout.js
- client/components/CART/OrderSummary.js
- client/components/CATEGORIES/EditCategory.js
- client/components/NAVBAR/Navbar.js
- client/components/NAVBAR/SearchBar.js
- client/components/ORDERS/AllOrders.js
- client/components/PRODUCTS/AllProducts.js
- client/components/REVIEWS/CreateReview.js
- client/components/REVIEWS/ProductReviews.js
- client/components/USERS/CreateUser.js
- client/components/USERS/EditUser.js
- client/components/USERS/SingleUser.js
- client/store/actionCreators/orderActionCreators.js
- client/store/actions/index.js
- client/store/reducers/orderReducer.js
- client/store/thunks/orderThunk.js
- client/store/thunks/userThunk.js
- server/api/routes/orderRoute.js
- server/api/routes/productRoute.js
- server/api/routes/reviewRoute.js
- user redirected to a page detailing their order summary after checkout
- cleans up some console logs
> feature: Checkout summary

- client/components/CART/Cart.js
- client/components/CART/OrderSummary.js
- server/api/routes/orderRoute.js
- server/api/routes/productRoute.js
- server/api/routes/userRoute.js
- product quantity decrements after user checks out their cart based on the items they buy
- destructures req.bodys for greater security
> update/cleanup: Req.body cleanup

- client/components/CATEGORIES/AllCategories.js
- client/components/CATEGORIES/CreateCategory.js
- client/components/NAVBAR/Home.js
- client/components/PRODUCTS/AllProducts.js
- client/components/SLIDES/ImageSlider.js
- client/components/SLIDES/SliderData.js
- package-lock.json
- package.json
- public/style.css
> Clean updates1

- client/components/ABOUT/About.js
- client/components/CATEGORIES/AllCategories.js
- client/components/CATEGORIES/CreateCategory.js
- client/components/CATEGORIES/EditCategory.js
- client/components/CATEGORIES/SingleCategory.js
- client/components/NAVBAR/Navbar.js
- client/components/NAVBAR/SearchBar.js
- client/components/ORDERS/SingleOrder.js
- client/components/PRODUCTS/AllProducts.js
- client/components/USERS/AllUsers.js
- client/components/USERS/EditUser.js
- client/components/USERS/SingleUser.js
- public/style.css
> update: Continued cart11

- client/components/PRODUCTS/AllProducts.js
- package-lock.json
- public/style.css
- server/api/routes/orderRoute.js
> update: more changes

- client/components/CATEGORIES/CreateCategory.js
- client/components/ORDERS/AllOrders.js
- client/components/SLIDES/ImageSlider.js
- client/components/USERS/EditUser.js
- client/store/thunks/categoryThunk.js
- client/store/thunks/orderThunk.js
- client/store/thunks/productThunk.js
- client/store/thunks/reviewThunk.js
- client/store/thunks/userThunk.js
- server/api/routes/categoryRoute.js
- server/api/routes/orderRoute.js
- server/api/routes/productRoute.js
- server/api/routes/reviewRoute.js
- server/api/routes/userRoute.js
- requires token for backend routes so that non admin users/users that shouldn't have access, don't
- passes token from frontend to backend
> update: secure backend

- client/components/CART/Checkout.js
- client/components/CART/OrderSummary.js
- client/components/CATEGORIES/SingleCategory.js
- client/components/NAVBAR/Home.js
- client/components/PRODUCTS/AllProducts.js
- client/components/USERS/CreateUser.js
- client/store/thunks/orderThunk.js
- client/store/thunks/userThunk.js
- public/index.html
- public/style.css
- server/api/routes/orderRoute.js
- server/db/models/User.js
> update: More cart

- client/components/ABOUT/About.js
- client/components/CATEGORIES/AllCategories.js
- server/api/routes/orderRoute.js
> last minute changes
